# sample makefile for an urbi module

#path where sdks are installed
PREFIX=/usr/local/

#default target (aibo, remote)
TARGET=remote

MODULENAME=module

include $(PREFIX)/share/urbicore/$(TARGET)/Makefile.param

CPPFLAGS += -I$(PREFIX)/share/urbicore/include
SOURCEPCC :=$(wildcard *.cc) 
SOURCECC := $(filter-out URBI.snap.cc umain.cc ,  $(SOURCEPCC))
SOURCECPP := $(wildcard *.cpp) 
SOURCEC := $(wildcard *.c)
HEADERS :=$(wildcard *.h)  $(wildcard *.hh)
OBJECTS := $(SOURCECC:%.cc=%.o)  $(SOURCECPP:%.cpp=%.o) $(SOURCEC:%.c=%.o)

module: lib$(MODULENAME).a

lib$(MODULENAME).a:  $(OBJECTS) 
	$(LD) -r -whole-archive $(LDFLAGS) -o lib$(MODULENAME).a $(OBJECTS)

link: module
	make -f  $(PREFIX)/share/urbicore/$(TARGET)/Makefile link "LIB_DIR=./ $(LIB_DIR)" "LIBS=$(MODULENAME) $(LIBS)"
	
clean:
	rm -f $(OBJECTS) lib$(MODULENAME).a: URBI.bin urbimodule

aibo:
	make TARGET=aibo link

remote:
	make TARGET=remote link

# Implicit rules
%.o: %.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $<

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $<

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ -c $<

