#!/bin/sh

set -e
dir=$1
if test x$dir = x; then
  dir=/usr/local
fi

echo "installing in $dir"
mkdir -p $dir

cp -ar bin gostai include lib share $dir

sed -e "s@^prefix=.*@prefix=$dir@" "$dir/bin/umake" > "$dir/bin/umake.tmp"
mv "$dir/bin/umake.tmp" "$dir/bin/umake"

chmod a+x $dir/bin/umake

echo "all done"
