UAbstractClient Class Reference
Interface for an URBI wrapper object.
#include <uabstractclient.h>
Public Member Functions
UAbstractClient (const char *_host, int _port=URBI_PORT, int _buflen=URBI_BUFLEN)
Create a new instance and connect to the Urbi server.
int error ()
Return current error status, or zero if no error occurred.
int send ()
Function for backward compatibility. Will be removed in future versions.
int send (const char *format,...)
Send an Urbi command. The syntax is similar to the printf()(p.) function.
int sendBin (const void *, int len)
Send binary data.
int sendBin (const void *, int len, const char *header,...)
Send an Urbi header followed by binary data.
int startPack ()
Lock the send buffer (for backward compatibility, will be removed in future versions).
int endPack ()
Unlock the send buffer (for backward compatibility, will be removed in future versions).
int pack (const char *,...)
Append Urbi commands to the send buffer (for backward compatibility, will be removed in future versions).
int vpack (const char *, va_list args)
va_list version of pack.
int sendFile (const char *filename)
Send urbi commands contained in a file.
UCallbackID sendCommand (UCallback, const char *,...)
Send a command, prefixing it with a tag, and associate the given callback with this tag. */.
UCallbackID sendCommand (UCustomCallback, void *, const char *,...)
Send a command, prefixing it with a tag, and associate the given callback with this tag. */.
int sendSound (const char *device, const USound &sound, const char *tag=0)
Send sound data to the robot for immediate playback.
int putFile (const char *localName, const char *remoteName=0)
Put a file on the robot's mass storage device.
int putFile (const void *buffer, int length, const char *remoteName)
Save a buffer to a file on the robot.
UCallbackID setCallback (UCallbackWrapper &callback, const char *tag)
Associate a callback function with a tag. new style.
UCallbackID setErrorCallback (UCallbackWrapper &callback)
Associate a callbaxk function with all error messages.
UCallbackID setWildcardCallback (UCallbackWrapper &callback)
Associate a callback with all messages.
UCallbackID setCallback (UCallback, const char *tag)
OLD-style callbacks.
UCallbackID setCallback (UCustomCallback, void *callbackData, const char *tag)
Associate a callback function with a tag, specifiing a callback custom value that will be passed back to the callback function.
template<class C> UCallbackID setCallback (C &ref, UCallbackAction(C::*)(const UMessage &), const char *tag)
Callback to class member functions(old-style).
template<class C, class P1> UCallbackID setCallback (C &ref, UCallbackAction(C::*)(P1, const UMessage &), P1, const char *tag)
template<class C, class P1, class P2> UCallbackID setCallback (C &ref, UCallbackAction(C::*)(P1, P2, const UMessage &), P1, P2, const char *tag)
template<class C, class P1, class P2, class P3> UCallbackID setCallback (C &ref, UCallbackAction(C::*)(P1, P2, P3, const UMessage &), P1, P2, P3, const char *tag)
template<class C, class P1, class P2, class P3, class P4> UCallbackID setCallback (C &ref, UCallbackAction(C::*)(P1, P2, P3, P4, const UMessage &), P1, P2, P3, P4, const char *tag)
int getAssociatedTag (UCallbackID id, char *tag)
Get the tag associated with a registered callback.
int deleteCallback (UCallbackID callBackID)
Delete a callback.
void makeUniqueTag (char *tag)
Fill tag with a unique tag for this client.
void notifyCallbacks (const UMessage &msg)
Simulate an Urbi message.
virtual void printf (const char *format,...)=0
Notify of an error.
virtual unsigned int getCurrentTime ()=0
Get time in milliseconds since an unspecified but constant reference time.
virtual void lockSend ()=0
Lock the send buffer for exclusive use by the current thread.
virtual void unlockSend ()=0
Unlock the send buffer.
const char * getServerName ()
Return the server name or IP address.
template<class C, class P1> UCallbackID setCallback (C &ref, UCallbackAction(C::*func)(P1, const UMessage &), P1 p1, const char *tag)
template<class C, class P1, class P2> UCallbackID setCallback (C &ref, UCallbackAction(C::*func)(P1, P2, const UMessage &), P1 p1, P2 p2, const char *tag)
template<class C, class P1, class P2, class P3> UCallbackID setCallback (C &ref, UCallbackAction(C::*func)(P1, P2, P3, const UMessage &), P1 p1, P2 p2, P3 p3, const char *tag)
Protected Member Functions
void processRecvBuffer ()
Called each time new data is available in recvBuffer.
virtual int effectiveSend (const void *buffer, int size)=0
Queue data for sending, returns zero on success, nonzero on failure.
virtual bool canSend (int size)=0
Check if successive effectiveSend()(p.) of cumulated size 'size' will succeed.
virtual void lockList ()=0
Lock receive and send portions of the code.
virtual void unlockList ()=0
Unlock receive and send portions of the code.
UCallbackID addCallback (const char *tag, UCallbackWrapper &w)
Add a callback to the list.
Protected Attributes
char * host
Host name.
int port
URBI Port.
int buflen
URBI Buffer length.
int rc
System calls return value storage.
char * recvBuffer
Reception buffer.
int recvBufferPosition
Current position in reception buffer.
Friends
class UClientStreambuf
Detailed Description
Interface for an URBI wrapper object.
Implementations of this interface are wrappers around the URBI protocol. It handles URBI messages parsing, callback registration and various formatting functions. Implementations of this interface should:
Redefine errorNotify() as a function able to notify the user of eventual errors.
Redfine the four mutual exclusion functions.
Redefine effectiveSend()(p.).
Fill recvBuffer, update recvBufferPosition and call processRecvBuffer()(p.) when new data is available.
Provide an execute()(p.) function in the namespace urbi, that never returns, and that will be called after initialization.
See the liburbi-cpp documentation for more informations on how to use this class.
Definition at line 229 of file uabstractclient.h.
Constructor & Destructor Documentation
UAbstractClient::UAbstractClient (const char * _host, int _port = URBI_PORT, int _buflen = URBI_BUFLEN)
Create a new instance and connect to the Urbi server.
Initializes sendBuffer and recvBuffer, and copy _host and _port.
Parameters:
_host IP address or name of the robot to connect to.
_port TCP port to connect to.
_buflen size of send and receive buffers. Implementations should establish the connection in their constructor.
Definition at line 166 of file uabstractclient.cpp.
References buflen, host, port, rc, and recvBuffer.
Member Function Documentation
int UAbstractClient::deleteCallback (UCallbackID callbackID)
Delete a callback.
Returns 0 if no callback with this id was found, 1 otherwise.
Definition at line 544 of file uabstractclient.cpp.
References lockList(), and unlockList().
Referenced by sendCommand(), and sendSound().
int UAbstractClient::getAssociatedTag (UCallbackID id, char * tag)
Get the tag associated with a registered callback.
Returns 1 and fills tag on success, 0 on failure
Definition at line 528 of file uabstractclient.cpp.
References lockList(), and unlockList().
void UAbstractClient::notifyCallbacks (const UMessage & msg)
Simulate an Urbi message.
Pass the given UMessage(p.) to all registered callbacks with the corresponding tag, as if it were comming from the URBI server.
Definition at line 140 of file uabstractclient.cpp.
References lockList(), UMessage::tag, UMessage::type, UCallbackAction, and unlockList().
Referenced by processRecvBuffer().
int UAbstractClient::pack (const char * command, ...)
Append Urbi commands to the send buffer (for backward compatibility, will be removed in future versions).
This function must only be called between a startPack()(p.) and the corresponding endPack()(p.). Data is queued in the send buffer, and sent when endPack()(p.) is called.
Definition at line 257 of file uabstractclient.cpp.
References rc, and vpack().
void UAbstractClient::processRecvBuffer () [protected]
Called each time new data is available in recvBuffer.
As long as this function has not returned, neither recvBuffer nor recvBufferPos may be modified.
Definition at line 654 of file uabstractclient.cpp.
References lockList(), notifyCallbacks(), printf(), recvBuffer, recvBufferPosition, and unlockList().
Referenced by UClient::listenThread().
int UAbstractClient::send (const char * command, ...)
Send an Urbi command. The syntax is similar to the printf()(p.) function.
Multiple commands can be sent in one call.
Definition at line 234 of file uabstractclient.cpp.
References effectiveSend(), lockSend(), rc, unlockSend(), and vpack().
int UAbstractClient::sendSound (const char * device, const USound & sound, const char * tag = 0)
Send sound data to the robot for immediate playback.
If tag is set, an URBI system `stop` message with this tag will be generated when the sound has been played. The sound data is copied in case of asynchronous send, and may be safely deleted as soon as this function returns.
Definition at line 469 of file uabstractclient.cpp.
References USound::channels, USound::data, deleteCallback(), makeUniqueTag(), USound::rate, USound::sampleFormat, USound::sampleSize, sendBin(), setCallback(), USound::size, and USound::soundFormat.
int UAbstractClient::startPack ()
Lock the send buffer (for backward compatibility, will be removed in future versions).
In threaded environnments, this function locks the send buffer so that only the calling thread can call the send functions. Otherwise do nothing.
Definition at line 215 of file uabstractclient.cpp.
References lockSend().
The documentation for this class was generated from the following files:
uabstractclient.h
uabstractclient.cpp