#!/bin/sh

set -e
. $(dirname "$0")/common

cd "$DIR_BUILD"

# Remove useless remains from previous "make dist" or "make packages".
rm -rf urbi-* urbi_*

# It may look stupid, but we sometimes have concurrency issues.
make -j ${JOBS} || make
