#!/bin/sh

set -xe

cd "$DIR_BUILD"

check_()
{
  make installcheck DESTDIR="$DIR_INSTALL" "$@"
}

check ()
{
  check_ -j$JOBS "$@" || check_ VERBOSE=1 "$@"
}

check -C tests TESTS_DIRS=0.x
check -C doc
check -C tests TESTS_DIRS=2.x
check -C tests TESTS_DIRS=1.x
check -C tests TESTS_DIRS=uob/plug
check -C tests TESTS_DIRS=uob/remote
check -C tests TESTS_DIRS=uob/java
check -C tests TESTS_DIRS=demo
# Cannot install-check fsm, since fsm.u is not installed.
# check -C tests TESTS_DIRS=@fsm
check -C tests TESTS_DIRS=@ros
