#!/bin/sh

set -e
. $(dirname "$0")/common

set -x

cd "$DIR_BUILD"
rm -rf "$DIR_INSTALL" "$DIR_STAGE"
mkdir -p "$DIR_STAGE"
make install DESTDIR="$DIR_STAGE"
make relocatable DESTDIR="$DIR_STAGE"
mv "$DIR_STAGE" "$DIR_INSTALL"
