#! /bin/sh

fatal ()
{
  echo >&2 "$0: $@"
  exit 1
}

# Failures do matter.
set -e

# The ast/ is generated, including its Makefile.
if test -f dev/ast-nodes-mk-gen && test -f src/ast/ast.yml; then
  python_check_mod_syck='
import sys, imp
try:
  imp.find_module("syck")
except ImportError:
  sys.exit(1)
'
  if ! python -c ''; then
    fatal "python is required"
  elif ! python -c "$python_check_mod_syck"; then
    fatal "Python module \`syck' is required"
  fi

  python dev/ast-nodes-mk-gen src/ast <src/ast/ast.yml \
    || {
      rv=$?
      cat >&2 <<EOF

-----------------------------------------------------------------------
If the last error is "./bootstrap: Python module \`syck' is required"
Then you need to install Python Bindings for Syck.
If it was "AttributeError: 'module' object has no attribute
'load_documents'", you need the latest version of PySyck.

In both cases, see:
  * Syck: http://whytheluckystiff.net/syck/
  * PySyck: http://pyyaml.org/wiki/PySyck
Or run install-pysyck, found in the install directory of the common
repository.

If it was "ImportError: No module named _syck"
Then check your install of PySyck (probably chmod -R a+rX python's
site-packages directory because python eggs don't know how to
properly chmod the files they install)
EOF
      (exit $rv); exit $rv
    }
fi

# Finally, install the GNU Build System and our submodules.
exec libport/build-aux/bootstrap "$@"
