/**
 ** \file ast/all.hh
 ** \brief Include all exported headers.
 */

#ifndef AST_ALL_HH
# define AST_ALL_HH

# include "ast/fwd.hh"
# include "ast/ast.hh"

// Why not include an autogenerated file here also?

#endif // !AST_ALL_HH
