#!/bin/sh

if [ ! -f fwd.hh ]
then
  echo "" > fwd.hh
fi

if [ ! -f visitor.hh ]
then
  echo "" > visitor.hh
fi

../../dev/ast-nodes-mk-gen < ast.yml > ast-nodes.mk
../../dev/ast-fwd-gen . < ast.yml
../../dev/ast-visitor-gen . < ast.yml
../../dev/ast-nodes-gen . < ast.yml
