#! /usr/bin/env python

import re
import sys
import ast, tools

if len(sys.argv) != 2:
  tools.error ("Usage: .. SRCDIR")
srcdir = sys.argv[1]

## Abstract syntax tree C++ Makefile.am ---------------------------------------
loader = ast.Loader ()
nodes, ast_params = loader.load (sys.stdin)

arr = nodes.values ()
arr.sort (lambda x, y: cmp(x.name, y.name))

# Output the files in an indented way: subclasses are more indented
# than super classes.  When there is multiple inheritance, consider
# only the first super class.

basedir = ast_params['ast_basedir']

mk = file("ast-nodes.mk.tmp",  "w")
print >>mk, "AST_headers =",
for node in arr:
  print >>mk, " \\\n  " + basedir + node.hh() + " " + basedir + node.hxx(),
print >>mk, "\n"

print >>mk, "AST_sources =",
for node in arr:
  print >>mk, " \\\n  " + basedir + node.cc(),
print >>mk, "\n"

print >>mk, "AST_NODES = $(AST_headers) $(AST_sources)"

mk.close()
tools.lazy_install (srcdir, "ast-nodes.mk")
