#!/usr/bin/env python

import sys
import ast, tools

if len (sys.argv) != 2:
  tools.error("Usage: .. SRCDIR")
srcdir = sys.argv[1]

## Abstract syntax tree C++ forward declarations ------------------------------
loader = ast.Loader ()
nodes, ast_params = loader.load (sys.stdin)

ignores = \
[
  "all.hh",
  "all.stamp",
  "ast-fwd-gen.stamp",
  "ast-nodes-gen.stamp",
  "ast-nodes.mk",
  "ast-print-visitor-gen.stamp",
  "ast-visitor-gen.stamp",
  "ast.dot",
  "cloner.cc",
  "cloner.hh",
  "cloner.stamp",
  "default-visitor.hh",
  "default-visitor.hxx",
  "default-visitor.stamp",
  "fwd.hh",
  "fwd.stamp",
  "graph.stamp",
  "ignores",
  "ignores.stamp",
  "nodes-mk.stamp",
  "nodes.stamp",
  "pretty-printer.cc",
  "pretty-printer.hh",
  "pretty-printer.hxx",
  "pretty-printer.stamp",
  "visitor.hh",
  "visitor.hxx",
  "visitor.stamp",
];

arr = nodes.values ()
for node in arr:
  ignores += [node.hh(), node.hxx(), node.cc()]
ignores.sort();

f = file ("ignores.tmp", "w")
for n in ignores:
  print >>f, n
f.close ()
tools.lazy_install (srcdir, "ignores");
