#!/usr/bin/env python

# TODO:
# - traversal of pointer types.
# - abstract classes should have a traversal too, let only to provide
#   it to its subclasses (via super_type::operator()).
# - subclasses should invoke the traversal of their superclass.

import re
import sys, os, os.path, filecmp, shutil, stat
import ast, tools
from string import lower

if len(sys.argv) != 2:
  tools.error("Usage: .. SRCDIR")
srcdir = sys.argv[1]

## Abstract syntax tree C++ visitor - header ----------------------------------
loader = ast.Loader ()
nodes, ast_params = loader.load (sys.stdin)

## --------------- ##
## The *.hh file.  ##
## --------------- ##

visitor_hh = file("default-visitor.hh.tmp", "w")

print >>visitor_hh, tools.banner("ast/default-visitor.hh",
		   "Definition of ast::DefaultVisitor.") + """
""" + ast_params['default_visitor_hh_prologue'] + """

namespace ast
{

  /** \\brief Just visit the whole Ast tree.
   **
   ** GenDefaultVisitor<CONSTNESS-SELECTOR> visits the whole Ast tree,
   ** but does nothing else. */
  template < template<typename> class Const >
  class GenDefaultVisitor : public GenVisitor<Const>
  {
  public:
    /// Super class type.
    typedef GenVisitor<Const> super_type;

    /** \\name Ctor & dtor.
     ** \\{ */
    /// Construct a Default Visitor.
    GenDefaultVisitor ();

    /// Destroy a Default Visitor.
    virtual ~GenDefaultVisitor ();
    /** \\} */

    // Import from super class.
    using super_type::operator();

    // Useful shortcut for pointer types.
    template<class E> void operator() (E* e);

    /* The following \\c typedef foo_type are only here to workaround a
     * bug in MSVC 2005 SP1, see:
     * http://forums.microsoft.com/msdn/showpost.aspx?postid=987536
     * http://support.microsoft.com/kb/930198 */

    /// \\name Visit nodes.
    /// \\{
"""
arr = nodes.values ()
arr.sort (lambda x, y: cmp(x.name, y.name))
for node in arr:
  # Do not output functions for abstract nodes, we might create
  # black holes: if the visitor runs into them, it won't get out.
  # Unless the user asks for troubles.
  if node.concrete or 'default' in node.__dict__:
    print >>visitor_hh, \
	"""
    /// MSVC 2005 SP1 workaround.
    typedef typename Const<%s>::type %s_type;
    virtual void operator() (%s_type&);
""" % (node.name, lower(node.name), lower(node.name))

print >>visitor_hh, """    /// \\}
  };

  /// Shorthand for a const visitor.
  typedef GenDefaultVisitor<libport::constify_traits> DefaultConstVisitor;
  /// Shorthand for a non const visitor.
  typedef GenDefaultVisitor<libport::id_traits> DefaultVisitor;

} // namespace ast

# include "ast/default-visitor.hxx"

#endif // !AST_DEFAULT_VISITOR_HH
"""


## ---------------- ##
## The *.hxx file.  ##
## ---------------- ##

visitor_hxx = file("default-visitor.hxx.tmp", "w")
sys.stdout = visitor_hxx

print >>visitor_hxx, tools.banner("ast/default-visitor.hxx",
				  "Implementation of ast::DefaultVisitor.") + """
# include "default-visitor.hh"
# include "all.hh"

namespace ast
{

  template <template <typename> class Const>
  GenDefaultVisitor<Const>::GenDefaultVisitor ()
    : GenVisitor<Const> ()
  {
  }

  template <template <typename> class Const>
  GenDefaultVisitor<Const>::~GenDefaultVisitor ()
  {
  }

  template <template <typename> class Const>
  template <class E>
  void
  GenDefaultVisitor<Const>::operator() (E* e)
  {
    e->accept (*this);
  }

"""

for node in arr:
  if node.concrete or 'default' in node.__dict__:
    if 'default' in node.__dict__:
      action = node.default
    else:
      action = ""
      for attr in node.attributes:
	if attr.visitable_p():
	  action += "    operator()(n." + attr.name + "_get());\n"
    if action != '':
      action = "\n" + action + "  "
      var = ' n'
    else:
      var = ''
    print """\
  template <template <typename> class Const>
  void
  GenDefaultVisitor<Const>::operator() (typename GenDefaultVisitor<Const>::%s_type&%s)
  {%s}
""" % (lower(node.name), var, action)

print """} // namespace ast
#endif // !AST_DEFAULT_VISITOR_HH
"""


# Restore stdout and close files
sys.stdout = sys.__stdout__
visitor_hh.close ()
visitor_hxx.close ()

tools.lazy_install(srcdir, "default-visitor.hh");
tools.lazy_install(srcdir, "default-visitor.hxx");
