    "BIN", "__HERE__", "and_eq", "asm", "assert", "at", "at&", "at,",
    "at;", "at|", "auto", "bitand", "bitor", "bool", "break", "call",
    "case", "catch", "char", "class", "closure", "compl", "const",
    "const_cast", "continue", "default", "delete", "detach", "disown",
    "do", "double", "dynamic_cast", "else", "enum", "every", "every&",
    "every,", "every;", "every|", "explicit", "export", "extern",
    "external", "finally", "float", "for", "for&", "for,", "for;",
    "foreach", "for|", "freezeif", "friend", "function", "goto", "if",
    "import", "in", "inline", "int", "internal", "isdef", "long", "loop",
    "loop&", "loop,", "loop;", "loop|", "mutable", "namespace", "onleave",
    "or_eq", "package", "private", "protected", "public", "register",
    "reinterpret_cast", "return", "self", "short", "signed", "sizeof",
    "static", "static_cast", "stopif", "struct", "switch", "template",
    "this", "throw", "timeout", "try", "typedef", "typeid", "typename",
    "union", "unsigned", "using", "var", "virtual", "volatile",
    "waituntil", "watch", "wchar_t", "when", "whenever", "while", "while&",
    "while,", "while;", "while|", 0
