/*
 * Copyright (C) 2010, Gostai S.A.S.
 *
 * This software is provided "as is" without warranty of any kind,
 * either expressed or implied, including but not limited to the
 * implied warranties of fitness for a particular purpose.
 *
 * See the LICENSE file for more information.
 * For comments, bug reports and feedback: http://www.urbiforge.com
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liburbi_main_UObjectJava */

#ifndef _Included_liburbi_main_UObjectJava
#define _Included_liburbi_main_UObjectJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liburbi_main_UObjectJava
 * Method:    registerNotifyOnRequest
 * Signature: (JLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_liburbi_main_UObjectJava_registerNotifyOnRequest
  (JNIEnv *, jobject, jlong, jstring, jboolean, jstring, jstring, jstring, jint);

/*
 * Class:     liburbi_main_UObjectJava
 * Method:    registerNotifyChange
 * Signature: (JLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_liburbi_main_UObjectJava_registerNotifyChange
  (JNIEnv *, jobject, jlong, jstring, jboolean, jstring, jstring, jstring, jint);

/*
 * Class:     liburbi_main_UObjectJava
 * Method:    registerFunction
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_liburbi_main_UObjectJava_registerFunction
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     liburbi_main_UObjectJava
 * Method:    registerTimerFunction
 * Signature: (Ljava/lang/Object;Ljava/lang/String;DLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_liburbi_main_UObjectJava_registerTimerFunction
  (JNIEnv *, jobject, jobject, jstring, jdouble, jstring, jstring, jstring, jint);


#ifdef __cplusplus
}
#endif
#endif
