Document: urbi-sdk2.7
Title: Debian urbi-sdk2.7 Manual
Author: <insert document author here>
Abstract: This manual describes what urbi-sdk2.7 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/urbi-sdk2.7/urbi-sdk2.7.sgml.gz

Format: postscript
Files: /usr/share/doc/urbi-sdk2.7/urbi-sdk2.7.ps.gz

Format: text
Files: /usr/share/doc/urbi-sdk2.7/urbi-sdk2.7.text.gz

Format: HTML
Index: /usr/share/doc/urbi-sdk2.7/html/index.html
Files: /usr/share/doc/urbi-sdk2.7/html/*.html
