#!/bin/sh


output_dir=sample
input_dir=examples
program_names=$(find $input_dir -name "*.java"				\
    -exec grep "public static .* main" "{}" \;				\
    -exec grep "public[ ]\+class" "{}" \;				\
    -exec echo "** {} ##" \;						\
    | grep -v "static"							\
    | sed 's/public[ ]\+class[ \t]*\([A-Za-z]\+\).*/\1/g'		\
    | tr -d '\n' | tr -d ' ' | sed -e 's/##/\n/g' | sed -e 's/\*\*/+/g')

for couple in $program_names; do
    name=$(echo $couple | cut -d '+' -f 1)
    dir=$(basename $(dirname $(echo $couple | cut -d '+' -f 2)))
    cat sample/template.launch > $output_dir/$name.launch.in;
    sed -i "s/@ECLIPSE_PROGRAM_MAIN@/examples.$dir.$name/g"  $output_dir/$name.launch.in
    sed -i "s/ECLIPSE_PROGRAM_ARGS/ECLIPSE_${name}_ARGS/g"  $output_dir/$name.launch.in
done

echo "
# This file was generated by $0.
# Please do not edit this file directly.
# Use the script provided to regenerate it.


"

echo "
if test \"x\$JAVA_HOME\" = \"x\"; then
  AC_MSG_ERROR([Environment variable JAVA_HOME is not set.])
fi

# Configure build.xml, the file used by ant to compile java code
AC_CONFIG_FILES([src/swig/java/build.xml])

JAVA_INCLUDE_DIR=
"

echo "case \$host_os in"
echo "    *mingw*|*cygwin*)"
echo "        JAVA_INCLUDE_DIR=win32"
read -p "
Specify the name of the environment variable containing paths to shared
library (ex: LD_LIBRARY_PATH on linux) under windows (default:'PATH'):" tmp
test "x$tmp" = "x" && tmp='PATH'
echo "	SHARED_LIBS_ENVVAR_NAME=\"$tmp\""
read -p "
Give the values you want to add to it (path1:path2:...) (default:'\${resource_loc:liburbi}/lib/'):" tmp
test "x$tmp" = "x" && tmp='\${resource_loc:liburbi}/lib/'
echo "	SHARED_LIBS_ENVVAR_VALUE=\"$tmp\""
echo "	;;"
echo "    *darwin*)"
echo "	SHARED_LIBS_ENVVAR_NAME=\"DYLD_LIBRARY_PATH\""
read -p "
Give the values you want to add to DYLD_LIBRARY_PATH under MacOs
(path1:path2:...) (default:'\${resource_loc:liburbi}/lib/'):" tmp
test "x$tmp" = "x" && tmp='\${resource_loc:liburbi}/lib/'
echo "	SHARED_LIBS_ENVVAR_VALUE=\"$tmp\""
echo "	;;"
echo "    *)"
echo "        JAVA_INCLUDE_DIR=linux"
echo "        SHARED_LIBS_ENVVAR_NAME=\"LD_LIBRARY_PATH\""
read -p "
Give the values you want to add to LD_LIBRARY_PATH under Linux
(path1:path2:...) (default:'\${resource_loc:liburbi}/lib/'):" tmp
test "x$tmp" = "x" && tmp='\${resource_loc:liburbi}/lib/'
echo "	SHARED_LIBS_ENVVAR_VALUE=\"$tmp\""
echo "	;;"
echo "esac"
echo
for couple in $program_names; do
    name=$(echo $couple | cut -d '+' -f 1)
    read -p "
Give the arguments of the program $name:" tmp
    echo "ECLIPSE_${name}_ARGS=\"$tmp\""
done
echo
echo "AC_SUBST([JAVA_INCLUDE_DIR])"
echo "AC_SUBST([SHARED_LIBS_ENVVAR_NAME])"
echo "AC_SUBST([SHARED_LIBS_ENVVAR_VALUE])"
for couple in $program_names; do
    name=$(echo $couple | cut -d '+' -f 1)
    echo "AC_SUBST([ECLIPSE_${name}_ARGS])"
done
echo
for couple in $program_names; do
    name=$(echo $couple | cut -d '+' -f 1)
    echo "AC_CONFIG_FILES([src/swig/java/$output_dir/$name.launch])";
done

echo "
## Local Variables:
## mode: autoconf
## End:
## vim:ft=config
"