#! /bin/sh
#

set -x
set -e

find_prog ()
{
  find_prog_res=
  local i
  for i in "$@"
  do
    if $i --version >/dev/null 2>&1; then
      find_prog_res=$i
      break
    fi
  done
}

stderr ()
{
  local i
  for i
  do
    echo >&2 "$0: $i"
  done
}

error ()
{
  local status="$1"
  shift
  stderr "$@"
  finalize
  exit $status
}

finalize ()
{
  rm -rf "$tmp"
}

## ----------- ##
## Variables.  ##
## ----------- ##

: ${TMPDIR=/tmp}

case $# in
  (8);;
  (*) fatal "not enough arguments: $#, expecting 8";;
esac

# Those would best be set through configure (except "updir"
# which sets the destination).

ARCH=$1       # ARM|x86|ppc
OS=$2         # linux|windows|macos
COMP=$3       # ex. gcc4
MODE=$4       # [release|debug]_[static|dynamic]
srcdir=$5
builddir=$6
DESTDIR=$7
upname=$8

# Do not produce anything if we are not working on windows builds.
case $OS in
  (windows) ;;
  (*) exit 0;;
esac

find_prog $MD5SUM gmd5sum md5sum
MD5SUM=$find_prog_res
test -n "$MD5SUM" ||
  fatal "cannot find md5sum"

cleanup ()
{
  status=$?
  cd /
  ls -l $tmp
  rm -rf $tmp
  exit $?
}
tmp=$(mktemp -d "$TMPDIR/kernel-make-installer.XXXXXX")
trap cleanup 0 1 2 13 15

updir=$(dirname "$upname")
basename=$(basename "${upname%-$MODE}")

release_zip=$basename.zip
debug_zip=$basename-debug_dynamic.zip
installer=$basename.exe

# my_zip represents the archive build by this slave.
case $MODE in
  (release)
    my_zip=$release_zip
    other_zip=$debug_zip
    ;;
  (debug*)
    my_zip=$debug_zip
    other_zip=$release_zip
    ;;
esac

if test -r "$updir/$my_zip"                             \
    -a -r "$updir/$other_zip"                           \
    -a "$updir/$my_zip" -nt "$updir/$other_zip"; then
  # My zip is the newest, do the merge-install.

  # Merge zips.
  tools=$HOME/share/tools
  vcredist="$tools/vcredist/vcredist_x86-$COMP.exe"
  gostai_console="$tools/gostai-console/Gostai Console 2.5-win32.exe"
  gostai_editor="$tools/gostai-editor/gostai-editor-2.4.1-win32.exe"
  $srcdir/scripts/merge-install.sh -v                   \
      --vcredist "$vcredist"                            \
      --comp "$COMP"                                    \
      --templateloc "$srcdir/share/templates"           \
      --installscriptloc "$srcdir/share/installer/"     \
      --gostai-console "$gostai_console"                \
      --gostai-editor "$gostai_editor"                  \
      --output "$tmp/$installer"                        \
      "$updir/$my_zip" "$updir/$other_zip"

  # Upload the installer and its MD5.  Be sure to generate an MD5sum
  # file that does not include a path: cd into
  here=$(pwd)
  cd $tmp
  $MD5SUM "$installer" >"$installer.md5"
  cp "$installer" "$installer.md5" "$updir"
  cd $here
fi
