#! /bin/sh
#

set -x
set -e

stderr ()
{
  local i
  for i
  do
    echo >&2 "$0: $i"
  done
}

error ()
{
  local status="$1"
  shift
  stderr "$@"
  finalize
  exit $status
}

finalize ()
{
  rm -rf "$tmp"
}

## ----------- ##
## Variables.  ##
## ----------- ##

: ${TMPDIR=/tmp}

case $# in
  (8);;
  (*) fatal "not enough arguments: $#, expecting 8";;
esac

# Those would best be set through configure (except "updir"
# which sets the destination).

ARCH=$1       # ARM|x86|ppc
OS=$2         # linux|windows|macos
COMP=$3       # ex. gcc4
MODE=$4       # [release|debug]_[static|dynamic]
srcdir=$5
builddir=$6
DESTDIR=$7
upname=$8

# Do not produce anything if we are not working on windows builds.
case $OS in
  (windows) ;;
  (*) exit 0;;
esac

tmp=$(mktemp -d "$TMPDIR/kernel-make-installer.XXXXXX")
trap "cd / && rm -rf $tmp" 0 1 2 13 15

updir=$(dirname "$upname")
basename=$(basename "${upname%-${MODE}}")

release_zip="$basename.zip"
debug_zip="$basename-debug_dynamic.zip"
installer="$basename.exe"

# my_zip represents the archive build by this slave.
case $MODE in
  (release)
    my_zip="$release_zip"
    other_zip="$debug_zip"
    ;;
  (debug*)
    my_zip="$debug_zip"
    other_zip="$release_zip"
    ;;
esac

if test -r "$updir/$my_zip"                             \
    -a -r "$updir/$other_zip"                           \
    -a "$updir/$my_zip" -nt "$updir/$other_zip"; then
  # My zip is the newest, do the merge-install.

  # Merge zips.
  tools=$HOME/share/tools
  vcredist="$tools/vcredist/vcredist_x86-${COMP}.exe"
  urbi_console="$tools/urbi-console/Gostai urbiConsole 2.1-win32.exe"
  $srcdir/scripts/merge-install.sh -v                   \
      --vcredist "$vcredist"                            \
      --comp "${COMP}"                                  \
      --templateloc "$srcdir/share/templates"           \
      --installscriptloc "$srcdir/share/installer/"     \
      --urbi-console "$urbi_console"                    \
      --output "$tmp/$installer"                        \
      "$updir/$my_zip" "$updir/$other_zip"

  # Upload the installer
  cp "$tmp/$installer" "$updir/$installer"
fi
